services:
  spliit2:
    image: spliit2:latest
    ports:
      - 3000:3000
    environment:
      - POSTGRES_PRISMA_URL=postgresql://postgres:1234@db
      - POSTGRES_URL_NON_POOLING=postgresql://postgres:1234@db
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
